Wenku/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views as account_views
from Files import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^channel/(?P<cid>\d+)/$', views.channel_files, name='channel_files'),
    url(r'^channel/(?P<cid>\d+)/first_category/(?P<fid>\d+)/$', views.first_category_files, name='first_category_files'),
    url(r'^list/(?P<cid>\d+)/first_category/(?P<fid>\d+)/second_category/(?P<sid>\d+)/$', views.second_category_files, name='second_category_files'),
    url(r'^search/(?P<type>\w+)/(?P<order>\w+)$', views.search, name='search'),
    url(r'^content/(?P<id>\d+)/$', views.content, name='content'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^GetFirstCategoryData/$',views.Return_First_Category_Data),
    url(r'^GetSecondCategoryData/$',views.Return_Second_Category_Data),
    url(r'^uploaded/$', views.uploaded, name='uploaded'),
    url(r'^signup/$', account_views.signup, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^user/$', views.user, name='user'),
    url(r'^review/$', views.review, name='review'),
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
]

Files/models.py
from django.db import models
from django.contrib.auth.models import User


class Channel(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_files_count(self):
        return File.objects.filter(second_category__first_category__channel=self).count()

    def get_files(self):
        return File.objects.filter(second_category__first_category__channel=self)

    def get_latest_files(self):
        return File.objects.filter(second_category__first_category__channel=self).order_by('-uploaded_at')[0:5]

    def get_hotest_files(self):
        return File.objects.filter(second_category__first_category__channel=self).order_by('-views')[0:9]

    def get_first_categories(self):
        return First_Category.objects.filter(channel=self)


class First_Category(models.Model):
    name = models.CharField(max_length=20)
    channel = models.ForeignKey(Channel, related_name='first_categories')

    def __str__(self):
        return self.name

    def get_files_count(self):
        return File.objects.filter(second_category__first_category=self).count()

    def get_files(self):
        return File.objects.filter(second_category__first_category=self)

    def get_latest_files(self):
        return File.objects.filter(second_category__first_category=self).order_by('-uploaded_at')[0:5]

    def get_hotest_files(self):
        return File.objects.filter(second_category__first_category=self).order_by('-views')[0:9]

    def get_second_categories(self):
        return Second_Category.objects.filter(first_category=self)


class Second_Category(models.Model):
    name = models.CharField(max_length=20)
    first_category = models.ForeignKey(First_Category, related_name='second_categories')

    def __str__(self):
        return self.name

    def get_files_count(self):
        return File.objects.filter(second_category=self).count()

    def get_files(self):
        return File.objects.filter(second_category=self)

    def get_latest_files(self):
        return File.objects.order_by('-uploaded_at')[0:5]

    def get_hotest_files(self):
        return File.objects.order_by('-views')[0:9]


class File(models.Model):

    name = models.CharField(max_length=30)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=400)
    content = models.TextField()
    ext = models.CharField(max_length=10)
    status = models.IntegerField(choices=((1, 'Normal'), (0, 'Converting'), (-1, 'Deleted'), (-2, 'FileDeleted')), default=1)
    page = models.PositiveIntegerField(null=True)
    MD5 = models.CharField(max_length=50)
    size = models.CharField(max_length=30)
    views = models.PositiveIntegerField(default=0)
    collects = models.PositiveIntegerField(default=0)
    downloads = models.PositiveIntegerField(default=0)
    file = models.FileField(upload_to='file', null=True)
    pdf_path = models.FileField(max_length=100, null=True)
    img_path = models.CharField(max_length=100, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(User, related_name='uploads')
    collected_by = models.ManyToManyField(User, related_name='collects', null=True)
    second_category = models.ForeignKey(Second_Category, related_name='files')


    def __str__(self):
        return self.name

    def get_latest_files(self):
        return File.objects.order_by('-uploaded_at')[0:3]

    def get_hotest_files(self):
        return File.objects.order_by('-views')[0:3]

    def get_files_count(self):
        return File.objects.all().count()

class SearchLog(models.Model):
    keyword = models.CharField(max_length=30)
    times = models.PositiveIntegerField(default=0)

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="icon" href="{% static 'img/logo1.png' %}">
    <title>{% block title %}我的文库{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Oswald|Pangolin|Raleway|Skranji" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/flat-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dochub.css' %}">
    {% block stylesheet %}{% endblock %}
</head>
<body>
{% block body %}
    <div class="container-fluid wenku-header">
  		<div class="container">
			<div class="col-xs-6">
				<a href="{% url 'home' %}" title="我的文库">
					<img alt="我的文库" class="wenku-logo" src="/static/img/logo1.jpg">
				</a>
			</div>
			<div class="col-xs-6">
				<form class="pull-right" action="{% url 'search' 'all' 'default'%}" target="_blank" method="get" role="search">
					<div class="input-group input-group-lg">
						<input type="text" required="required" name="wd" placeholder="请输入搜索关键字" class="form-control">
						<span class="input-group-btn"><button type="submit" class="btn btn-default">文库搜索</button></span>
					</div>
				</form>
			</div>
	  	</div>
  	</div>
    <nav class="container-fluid navbar-inverse navbar navbar-default hidden-mobile" role="navigation">
		<div class="container">
			<ul class="nav navbar-nav">
				<li class="active"><a href="{% url 'home' %}">首页</a></li>
				<li><a href="{% url 'channel_files' 1%}">编程开发</a></li>

				<li><a href="{% url 'channel_files' 2%}">系统运维</a></li>

				<li><a href="{% url 'channel_files' 3%}">设计·创作</a></li>

				<li><a href="{% url 'channel_files' 4%}">云计算·大数据</a></li>

				<li><a href="{% url 'channel_files' 5%}">产品·运营·综合</a></li>

			</ul>
			 <ul class="nav navbar-nav navbar-right">
		      <li><a href="{% url 'upload' %}"><span class="fa fa-upload"></span> 上传文档</a></li>
		      <li><a href="{% url 'user' %}"><span class="fa fa-user"></span> 会员中心</a></li>
		    </ul>
		</div>
	</nav>

        {% block content %}
        {% endblock %}
    <div class="container-fluid wenku-footer">
    	<div class="container">
    		<div class="row wenku-flink">
    			<div class="col-xs-12">
    				<div><strong>友情链接</strong></div>
    				<div class="help-block">

    					<a href="https://www.djangoproject.com/" target="_blank" title="Django">Django</a>

    					<a href="https://www.python.org/" target="_blank" title="Python">Python</a>

    					<a href="https://github.com/" target="_blank" title="Github">Github</a>

    					<a href="https://www.mysql.com/" target="_blank" title="MySQL">MySQL</a>

    				</div>
    			</div>
    		</div>
    	</div>
    </div>
    <div class="container-fluid wenku-footer-dark">
    	<div class="container">
    		<div class="row">
    			<div class="col-xs-12 text-center wenku-help help-block">

						<a href="#" target="_blank" title="关于我们">关于我们</a>

						<a href="#" target="_blank" title="关于我们">文库协议</a>

						<a href="#" target="_blank" title="意见反馈">意见反馈</a>

						<a href="#" target="_blank" title="免责声明">免责声明</a>

						<a href="" target="_blank" title="意见反馈">联系我们</a>

    			</div>
    			<div class="col-xs-12 text-center help-block">
					我的文库&nbsp;&nbsp;©2019&nbsp;&nbsp;<span class="text-muted">|</span>&nbsp;&nbsp;<a href="#" title="站点地图" target="_blank">站点地图</a>
    			</div>
    			<div class="col-xs-12 text-center help-block">
					<small>    				Powered By <a href="#" style="color: #1abc9c;" target="_blank" title="Django">Django</a> v1.1
                    </small>
    			</div>
			</div>
    	</div>
    </div>
{% endblock body %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery.lazyload.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/flat-ui.js' %}"></script>
<script src="{% static 'js/dochub.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center logo my-4">
            <a href="{% url 'home' %}">Wenku</a>
        </h1>
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
	<div class="row mobile-banner">

		<div class="col-xs-3 wenku-nopadding wenku-pdl-15px pull-right">
			<div class="panel panel-default text-center wenku-noradius wenku-noborder wenku-count clearfix">
				<div class="col-xs-6 wenku-nopadding">
					<div class="help-block">收录文档</div>
					<span class="text-primary">{{file_count}}</span>
				</div>
				<div class="col-xs-6 wenku-nopadding">
					<div class="help-block">注册用户</div>
					<span class="text-primary">{{user_count}}</span>
				</div>
			</div>
            <div class="panel panel-default text-center wenku-noradius clearfix wenku-noborder">
          <button class="col-xs-12 btn btn-default btn-lg"><a href="{% url 'login' %}"> 登录账号</a></button>
            </div>
            <div class="panel panel-default text-center wenku-noradius clearfix wenku-noborder">
          <button class="col-xs-12 btn btn-primary btn-lg"><a href="{% url 'signup' %}"> 注册账号</a></button>
            </div>
		</div>

        <div class="col-xs-9 wenku-nopadding pull-left">
            <div id="wenku-carousel" class="carousel slide">
                <ol class="carousel-indicators">

                    <li data-target="#wenku-carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#wenku-carousel" data-slide-to="1"></li>
                    <li data-target="#wenku-carousel" data-slide-to="2"></li>
                    <li data-target="#wenku-carousel" data-slide-to="3"></li>

                </ol>
                <div class="carousel-inner">
                    <a href="#" target="_blank" title="#" class="item active">
                        <img src="/static/img/banner1.jpg" alt="#">
                        <div class="carousel-caption"></div>
                    </a>
                    <a href="#" target="_blank" title="#" class="item">
                        <img src="/static/img/banner2.jpg" alt="#">
                        <div class="carousel-caption"></div>
                    </a>
                    <a href="#" target="_blank" title="#" class="item">
                        <img src="/static/img/banner3.jpg" alt="#">
                        <div class="carousel-caption"></div>
                    </a>
                    <a href="#" target="_blank" title="#" class="item">
                        <img src="/static/img/banner4.jpg" alt="#">
                        <div class="carousel-caption"></div>
                    </a>
                </div>
                <a class="carousel-control left" href="#wenku-carousel" data-slide="prev"><span class="fa fa-angle-left"></span></a>
                <a class="carousel-control right" href="#wenku-carousel" data-slide="next"><span class="fa fa-angle-right"></span></a>
            </div>
        </div>

	</div>


</div>

<div class="container-fluid wenku-cate">
	<div class="container">
		<div class="row">
        {% for channel in channels %}
            {% ifnotequal channel.id 5 %}
			<div class="col-xs-3">
				<div class="h5">{{ channel.name }}</div>
				<div class="wenku-cate-list">
                    {% for category in channel.get_first_categories %}
					<a href="{% url 'first_category_files' channel.id category.id %}">{{ category.name }}</a>
                    {% endfor %}
				</div>
			</div>
            {% endifnotequal %}
        {% endfor %}
		</div>
	</div>
</div>

<div class="container">

	<div class="row wenku-item">
		<div class="col-xs-6">
			<div class="panel panel-default wenku-noborder">
				<div class="panel-heading"><strong>热门推荐</strong></div>
				<div class="panel-body">
					<a href="javascript:void(0);" class="col-xs-5 wenku-nopadding">
						<img src="/static/img/cover-news1.png"/>
					</a>
					<div class="col-xs-7 wenku-nopadding">
						<ul>
							{% for file in files %}
							<li>
								<a href="{% url 'content' file.id %}" target="_blank" title="{{ file.name }}" class="wenku-text-ellipsis">
                                    <img alt="{{ file.ext }}文档" src="/static/img/{{ file.ext }}_24.png"> {{ file.name }}
								</a>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>

        {% for channel in channels %}

		<div {% if forloop.counter0|divisibleby:2 %} class="col-xs-6 wenku-mgl-15px" {% else %} class="col-xs-6" {% endif %}>
			<div class="panel panel-default wenku-noborder">
				<div class="panel-heading"><strong>{{ channel.name }}</strong>
					<a href="{% url 'channel_files' channel.id %}" target="_blank" title="{{ channel.name }}" class="pull-right text-muted">更多>></a>
				</div>
				<div class="panel-body">
					<a href="{% url 'channel_files' channel.id %}" title="{{ channel.name }}" target="_blank" class="col-xs-5 wenku-nopadding">
						<img alt="{{ channel.name }}" style="width: 195px;height: 154px;" src="/static/img/cover-news{{ forloop.counter|add:1 }}.png" onerror="this.src='/static/img/cover-news{{ forloop.counter|add:1 }}.png'"/>
					</a>
					<div class="col-xs-7 wenku-nopadding">
						<ul>
							{% for file in channel.get_latest_files %}
								<li>
									<a href="{% url 'content' file.id %}" target="_blank" title="{{ file.name }}" class="wenku-text-ellipsis">
										<img alt="{{ file.ext }}文档" src="/static/img/{{ file.ext }}_24.png"> {{ file.name }}
									</a>
								</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
    {% if forloop.counter0|divisibleby:2 %}
		</div>
		<div class="row wenku-item">
	{% endif %}

		{% endfor %}

	</div>
</div>


{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to Django Wenku{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Log in</h3>
                    <form method="post" novalidate>
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">
                        {% include 'includes/form.html' %}
                        <button type="submit" class="btn btn-primary btn-block">Log in</button>
                    </form>
                </div>
                <div class="card-footer text-muted text-center">
                    New to Django Wenku? <a href="{% url 'signup' %}">Sign up</a>
                </div>
            </div>
            <div class="text-center py-2">
                <small>
                    <a href="{% url 'password_reset' %}" class="text-muted">Forgot your password?</a>
                </small>
            </div>
        </div>
    </div>
{% endblock %}

templates/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/upload.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/upload.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="strong">文档上传</div>
            </div>
            <div class="panel-body">
                <div class="col-xs-8">
                    <form class="form-horizontal wenku-form-upload" role="form" method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">文档上传 <i class="text-danger">*</i></label>
                            <div class="col-sm-10">
                                <input type="file" required="required" data-err="请上传一篇文档" class="form-control" data-maxsize="52428800" data-accept="doc,docx,ppt,pptx,xls,xlsx,txt,pdf" name="file" placeholder="请上传一篇文档">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">文档名称 <i class="text-danger">*</i></label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" data-err="请输入文档名称" required="required" name="title" placeholder="请输入文档名称">
                                <input type="hidden" name="Filename">
                            </div>
                        </div>
                        <div class="form-group form-chanel">
                            <label class="col-sm-2 control-label">文库频道 <i class="text-danger">*</i></label>
                            <div class="col-sm-10">
                                <select name="channel" id="id_channel" onchange="Get_Next_Category('id_channel', 'Get_first_category')" required="required" data-err="请选择文库频道" class="form-control">
                                    <option id="Not_data1">请选择文库频道</option>
                                    {% for channel in channels %}
                                        <option id="{{ channel.name }}">{{ channel.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group form-cate">
                            <label class="col-sm-2 control-label">文档分类 <i class="text-danger">*</i></label>
                            <div class="col-sm-5 form-level-one">
                                <select name="first_category" id="id_first_category" onchange="Get_Next_Category('id_first_category', 'Get_second_category')" required="required" data-err="请选择一级文档分类" class="form-control">
                                    <option id="Not_data2">请先选择文库频道</option>
                                </select>
                            </div>
                            <div class="col-sm-5 form-level-two">
                                <select name="second_category" id="id_second_category" required="required" data-err="请选择二级文档分类" class="form-control">
                                    <option id="Not_data3">请先选择一级文档分类</option>
                                </select>
                            </div>
                        </div>
                        <input type="hidden" name="Md5" value="">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">文档简介 <i class="text-danger">*</i></label>
                            <div class="col-sm-10">
                                <textarea name="description" required="required" rows="7" class="form-control" placeholder="请输入文档的相关简介，让大家更容易找到文档"></textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-block btn-primary btn-lg">确定上传文档</button>
                    </form>
                </div>

                <div class="col-xs-4">
                    <div class="panel panel-default">
                        <div class="panel-body wenku-nopadding">
                            <div class="strong">温馨提示</div>
                            <div class="help-block">
                                1.带有 <i class="text-danger">*</i> 为必填项。同时<span class="text-success strong">建议填写文档标签和文档简介，方便自己和他人更快更准确地找到需求文档</span>。
                            </div>
                            <div class="help-block">
                                2.允许上传的最大文档为：<span class="strong text-primary">50MB</span>。
                            </div>
                            <div class="help-block">
                                3.分享，让知识传承更久远。<a href="/" target="_blank" title="我的文库">我的文库</a>致力于成为最大的行业文库平台，在尊重知识产权的前提下，让更多的人平等地获取知识。
                            </div>
                            <div class="help-block">
                                4.目前支持的文档类型：
                                <p>
                                    <img src="/static/img/doc_24.png" alt="Word文档" /> doc，docx
                                </p>
                                <p>
                                    <img src="/static/img/ppt_24.png" alt="PPT文档" /> ppt，pptx
                                </p>
                                <p>
                                    <img src="/static/img/xls_24.png" alt="XLS文档" /> xls，xlsx
                                </p>
                                <p>
                                    <img src="/static/img/txt_24.png" alt="TXT文档" /> txt
                                </p>
                                <p>
                                    <img src="/static/img/pdf_24.png" alt="PDF文档" /> pdf
                                </p>
                            </div>
                            <div class="help-block">5.上传涉嫌侵权或违法的文档将会被移除。</div>
                            <div class="help-block">6.上传有问题需要帮助？请查看 <a href="#" target="_blank" title="文库帮助">文库帮助</a> 和 <a href="#" target="_blank" title="意见反馈">意见反馈</a></div>
                            <div class="help-block">7.为营造绿色网络环境，严禁上传含有淫秽色情及低俗信息等文档，让我们一起携手共同打造健康文库</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
        //用来获得option元素中selected属性为true的元素的id
        function Get_Selected_Id(id){
            var pro = document.getElementById(id);
            var Selected_Id = pro.options[pro.selectedIndex].id;
//            console.log("Get_Selected_Id:"+Selected_Id);  //测试使用
            return Selected_Id;         //返回selected属性为true的元素的id
        }

        //执行相应的动作，调用相关数据请求函数
        function Get_Next_Category(Channel_ID,Action){
            var Selected_Id = Get_Selected_Id(Channel_ID);   //Selected_Id用来记录当前被选中的省或市的ID
            if(Action=='Get_first_category')                            //从而可以在下一个级联中加载相应的市或县
                Get_First_Category_Data(Selected_Id);
            else if(Action=='Get_second_category')
                Get_Second_Category_Data(Selected_Id);
        }

        //向服务器请求城市列表数据并调用添加城市函数
        function Get_First_Category_Data(Channel_Selected_Id){    //这里的Selected_Id应该是被选中的省份的ID
//            console.log("Channel_Selected_Id:"+Channel_Selected_Id);   //测试使用
            if(Channel_Selected_Id == 'Not_data1'){    //如果选择了"Province"选项，则表示重置当前City和Country的选项内容，不会向服务器请求数据
                $("#id_first_category").empty();
                $("#id_first_category").append("<option id='Not_data2'>请先选择文库频道</option>");
                $("#id_second_category").empty();
                $("#id_second_category").append("<option id='Not_data3'>请先选择一级文档分类</option>");
            }else{      //否则就会向服务器请求数据
                $.getJSON('/GetFirstCategoryData/',{'Channel':Channel_Selected_Id},function(First_Category_list){
//                    console.log(First_Category_list);      //测试使用
                    Add_first_category(First_Category_list);    //调用添加城市选项函数
                });
            }
        }

        //在当前页面添加城市选项
        function Add_first_category(First_Category_list){
            $("#id_first_category").empty();
            $("#id_first_category").append("<option id='Not_data2'>请先选择文库频道</option>");
            $("#id_second_category").empty();
            $("#id_second_category").append("<option id='Not_data3'>请先选择一级文档分类</option>");
            //上面的两次清空与两次添加是为了保持级联的一致性
            for(var index in First_Category_list){     //获得城市列表中的城市索引
                //添加内容的同时在option标签中添加对应的城市ID
                var text = "<option"+" id='"+First_Category_list[index]+"'>"+First_Category_list[index]+"</option>";
                $("#id_first_category").append(text);
                console.log(text);  //用来观察生成的text数据
            }
        }

        //向服务器请求县区列表数据并调用添加县区函数
       function Get_Second_Category_Data(First_Category_Selected_Id){
//           console.log("First_Category_Selected_Id:"+First_Category_Selected_Id);   //测试使用
           if(First_Category_Selected_Id == 'Not_data2'){     //如果选择了City选项，则表示重置当前Country的选项内容，不会向服务器请求数据
               $("#id_second_category").empty();
               $("#id_second_category").append("<option id='Not_data3'>请先选择一级文档分类</option>");
               //上面的清空与添加是为了保持级联的一致性
           }else{   //否则就会向服务器请求数据
               var Channel_Selected_ID = Get_Selected_Id("id_channel");  //获得被选中省的ID，从而方便从服务器中加载数据
               $.getJSON('/GetSecondCategoryData/',{'Channel':Channel_Selected_ID,'First_Category':First_Category_Selected_Id},function(Second_Category_list){
//                   console.log(Second_Category_list);    //测试使用
                   Add_second_category(Second_Category_list);   //调用添加县区选项函数
               });
           }
        }

        //在当前页面添加县区选项
        function Add_second_category(Second_Category_list){
            $("#id_second_category").empty();
            $("#id_second_category").append("<option id='Not_data3'>请先选择一级文档分类</option>");
            //上面的清空与添加是为了保持级联的一致性
            for(var index in Second_Category_list){     //获得县区列表中的县区索引
                //添加内容的同时在option标签中添加对应的城市ID
                var text = "<option"+" id='"+Second_Category_list[index]+"'>"+Second_Category_list[index]+"</option>";
                $("#id_second_category").append(text);
                console.log(text);  //用来观察生成的text数据
            }
        }

    </script>
        <iframe frameborder="0" style="display: none;" id="notarget" name="notarget"></iframe>
    </div>
</div>

{% endblock %}

templates/uploaded.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
    <div class="alert alert-success">
        成功上传文档！
    </div>
      <div class="btn-group">
          <button class="btn btn-default"><a href="{% url 'user' %}"> 查看已上传文档</a></button>
          <button class="btn btn-primary"><a href="{% url 'upload' %}"> 继续上传文档</a></button>
      </div>
    </div>
{% endblock %}